name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          cd shipping_backend
          pip install -r requirements.txt

      - name: Download Model from Google Drive
        run: |
          FILE_ID=1itUvANQGCf3xNf83W4fYDzUYStSVbtmK
          curl -L -o phishing_model.zip "https://drive.google.com/uc?export=download&id=$FILE_ID"
          unzip phishing_model.zip -d phishing_model

      - name: Run tests
        run: |
          cd shipping_backend
          pytest shipping_backend/tests/
