name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          cd shipping_backend
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ../shipping_backend # Add shipping_backend to Python path
        run: |
          pytest shipping_backend/tests/
