name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          cd shipping_backend
          pip install -r requirements.txt

      - name: Install gdown
        run: pip install gdown

      - name: Download Model from Google Drive
        run: |
          gdown "https://drive.google.com/uc?id=1itUvANQGCf3xNf83W4fYDzUYStSVbtmK" -O phishing_model.zip
          unzip phishing_model.zip -d phishing_model
          ls -l phishing_model  # List contents of the model folder to verify download

      - name: List files in phishing_model directory
        run: |
          ls -l phishing_model

      - name: Run tests
        env:
          PYTHONPATH: ./shipping_backend
        run: |
          cd shipping_backend
          pytest tests/
