name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          cd shipping_backend
          pip install -r requirements.txt

      - name: Install gdown
        run: pip install gdown

      - name: Download Model from Google Drive
        run: |
          gdown -O phishing_model.zip https://drive.google.com/uc?export=download&id=1itUvANQGCf3xNf83W4fYDzUYStSVbtmK
          if [ -f "phishing_model.zip" ]; then
            unzip phishing_model.zip -d phishing_model
          else
            echo "phishing_model.zip not found, download failed."
            exit 1
          fi

      - name: Run tests
        run: |
          cd shipping_backend
          pytest shipping_backend/tests/
